### ISSUE TITLE
Promoting pawn

### ISSUE THREAD

**Issue by nowakprojects** [nowakprojects/CodersCamp2019.Projekt2.Szachy#7]
When pawn reach the end of the board,
the window with options to promote should be shown.

After choose replace the pawn with the new piece.

There knwoledge from the Chapter III of course will be helpful.

Podzadania:

- [ ] Napisz test sprawdzający czy promotePawn(pawnSquare, newPiece) z klasy ChessGame jest możliwe tylko dla piece o klasie Pawn. Zaimplementuj sprawdzanie klasy z wyniku metody rchessBoard.getPiece(pawnSquare)

- [ ] Napisz test czy po promotePawn piece został zamieniony na wybrany newPiece. Zaimplementuj zamienianie.

- [ ] Napisz test sprawdzający czy promotePawn jest możliwe tylko dla newPiece takich jak w prawdziwych szachach. Zaimplementuj sprawdzanie :) 

- Napisz test sprawdzający czy promotePawn jest wykonywany na pawnSquare, który jest na końcu szachownicy dla danego Pawna. Zaimplementuj to co test testuje :) 

- [ ] Ogólnie: Utwórz w klasie ChessGame metode promotePawn(pawnSquare, newPiece)
Metoda powinna wyszukiwać pionek po pawnSquare, sprawdzać czy jest to pawn i jeśli tak to podmieniać go z figurę newPiece (pamiętaj o niemutowalności chessboard!).

- [ ] W callbacku dla pieceMoved w ChessBoardView sprawdzaj czy jest to pionek, który doszedł do końca szachownicy, jeśli tak to wykonaj metodę showPromoteModal()

- [ ] Po wykonaniu powyższych punktów przenij zadanie na @nowakprojects. @nowakprojects  doimplementuje część wizualną. Oczywiście możesz to też robić sama @ewzdun  - tym lepiej.

**Comment by nowakprojects** [comment]
> Hej, mam problem trochę z zadaniem.
> Mam utworzyć metodę promotePawn(pawnSquare, newPiece), która najpierw powinna wyszukać pionek po pawnSquare... to znaczy rozumiem, że po prostu powinna sprawdzić, czy dany pionek faktycznie dotarł na drugi koniec planszy ? jeśli biały to na nr 8, a jeśli czarny to na wiersz nr 1? Tylko nie do końca wiem, w jaki sposób technicznie to zrobić. bo skąd ma się wziąć parametr pawnSquare, skoro on nie jest nigdzie wczesniej zapisany?
> po drugie, ta sama metoda, ma później sprawdzić czy ten pionek to Pawn, ale skoro pierwszy parametr to 'pawnSquare' to chyba nie ma opcji zeby to byl inny pionek ?

Hmmm... dobre pytanie skąd ma się wziąć pawnSquare. Załóżmy, że się weźmie a jak to zaraz poniżej :) Dobrze to sprawdzać, bo metoda powinna być "idiotoodporna". Nie możemy być 100% pewni, że jakiś developer nie wywoła sobie promotePawn np. na samym początku gry. Dlatego też sprawdzamy:
1. Czy na pawnSquare stoi Pawn. 
2. Czy pawnSquare jest na końcu planszy tak jak właśnie napisałaś.

> po trzecie, jak wszystko wyżej się zgadza, metoda ma ten pionek podmienić z figurą newPiece. i tego też nie umiem sobie wyobrazić jak to technicznie zrobić. rozumiem, że gdy pawn dotrze do końca planszy ma się pojawić jakieś okienko pytające gracza, na jaką figurę chce zamienić pawna ?

Tak, pojawi się okienko. Chcesz je robić, czy zakładamy, że ja je zrobię (takie było wstępne założenie) :) ? Jak tak to mogę to dzisiaj zrobić. 
Załóżmy, że metoda showPromotePawnModal będzie przyjmować jako argument pawnSquare. Po wybraniu na jaką figurę zmienić pionka wywoła właśnie promotePawn z tym argumentem + jeszcze newPiecie. Masz rację, tutaj była luka rozumowania.

> Nie chcę mówić, że zadanie mnie przerosło, bo to jeszcze nie koniec :smile: ale zabierałam się do tego jak pies do jeża, usiadłam i rozumiem o co chodzi, ale nie wiem jak ugryźć. pytam na razie o pierwsze podzadanie za jakie się wzięłam, oby po odpowiedzi rozjaśniło się tez coś w kolejnych. :stuck_out_tongue:

**Comment by ewzdun** [comment]
Dzięki, idę sobie teraz to poukładać w głowie :D odezwę się jeszcze na pewno ;P
Postaram się zrobic okienko, chyba że totalnie braknie mi czasu :)

**Comment by nowakprojects** [comment]
> Dzięki, idę sobie teraz to poukładać w głowie :D odezwę się jeszcze na pewno ;P
> Postaram się zrobic okienko, chyba że totalnie braknie mi czasu :)

OK, jakiekolwiek pytanie będziesz miała to pisz :) Najlepiej tutaj, ale dawaj też dać na Slacku, że napisałaś. 
A propos okienka - jeśli mam zrobić, to daj mi znać do czwartku :) Bo musimy mieć czas na spięcie wszystkiego razem. Proponowałbym, żebyś jednak Ty to zrealizowała, bo w trakcie kursu i tak każdy musi zrobić zadania, gdzie wykorzysta JS na froncie, to wtedy będziesz to już miała za sobą :)

**Comment by ewzdun** [comment]
Mam znów wątpliwości...
W klasie chessBoardView napisałam na razie taka metodę 
`    checkingPromote(pieceMoved) {
        if (pieceMoved.to.row === 0 && pieceMoved.piece.side === "white") {
            showPromoteModal(pawnSquare)
        } else if (pieceMoved.to.row === 7 && pieceMoved.piece.side === "black") {
            showPromoteModal(pawnSquare)
        }
    }`
Sprawdza, czy pionek, który właśnie się ruszył, dotarł na koniec planszy i jeśli tak to wywołuje się showPromoteModal z argumentem pawnSquare (bo tak jest napisane w podzadaniu). Tylko tak myślę, czy to raczej nie powinno wywoływac metody z chessGame promotePawn. Ona by sprawdzała, czy to pionek i jeśli tak to by pytało gracza, na jaką figurę zmienia. Dobrze myślę czy mieszam ?

Bo inaczej nie umiem sobie wyobrazić, jak te dwa podzadania miałyby ze sobą 'współpracować'

**Comment by ewzdun** [comment]
I czy okienko to po prostu prompt ?

**Comment by nowakprojects** [comment]
@ewzdun No właśnie trochę mieszasz :) Bo nie możemy powiązać warstwy logiki (sama gra w szachy) z warstwą UIa (presentation). Jeśli promotePawn w chessGame miałby pokazywać prompt to to miesza. Dla zwykłego działania możesz zrobić prompt, jak starczy czasu zamienimy to na okno modalne pokazujące się i z figurkami do wyboru. 
checkingPromote na pewno nam się przyda :) Tylko jeszcze czy to jest na pewno Pawn.
Zobacz, nasza gra samo chessGame nie musi wiedzieć, w jaki sposób Ty coś wybrałaś, to już kwestia właśnie UIa. 

Czyli to jest tak:
1. Po ruchu UI wie, że ma wyświetlić okienko, jak to jest właśnie true checkingPormote.
2. Wyświetla okienko i wybierasz na co chcesz zmienić.
3. Na chessGame wykonujesz zamianę szachów (to Ci sprawdza czy to pion itp.). 

Nie ma jakos zrobić, żęby chessGame pytał gracza, bo to kwestia samego widoku.

**Comment by nowakprojects** [comment]
Aleee! Możesz zrobić tak, żeby to działało, a potem bedziemy się zastanawiać czy da się zrobić lepiej :) Zazwyczaj jak się programuje to robisz tak, żeby zadziałało, a potem poprawiasz.
